# remap prefix from 'C-b' to 'M-a'
unbind C-b
set-option -g prefix M-C-Space
bind-key M-C-Space send-prefix

set -g aggressive-resize on               # aggressive resize
set -sg escape-time 0                     # escape time
set -g base-index 1                       # set initial window index to 1

bind x kill-pane                                 # kill pane without confirmation
bind k kill-window                               # kill window
bind q kill-session                              # kill session

# split panes using | and -
unbind '"'
unbind %
bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"

bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

# Toggle quickly between last windows

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on


# Increase the history limit
set-option -g history-limit 5000

# Change the status bar color
set -g default-terminal "screen-256color"
set -g status-bg grey12
set -g status-fg color7

setw -g window-status-style fg=grey70
set-window-option -g window-status-current-style fg=grey99,bold


