window.system.main.minimized=false
window.system.main.visible=true
window.system.main.x=-13
window.system.main.y=98
window.chest.minimized=false
window.chest.visible=true
window.chest.x=100
window.chest.y=190
window.character.minimized=false
window.character.visible=true
window.character.x=2
window.character.y=2
window.examine.minimized=false
window.examine.visible=true
window.examine.x=0
window.examine.y=0
window.bag.minimized=false
window.bag.visible=true
window.bag.x=2
window.bag.y=2
window.quit.minimized=false
window.quit.visible=false
window.quit.x=0
window.quit.y=0
window.spells.minimized=false
window.spells.visible=true
window.spells.x=2
window.spells.y=2
window.system.settings.minimized=false
window.system.settings.visible=true
window.system.settings.x=0
window.system.settings.y=0
window.corpse.minimized=false
window.corpse.visible=true
window.corpse.x=0
window.corpse.y=190
window.keyring.minimized=false
window.keyring.visible=true
window.keyring.x=2
window.keyring.y=2
config.ui.window_order=character;bag;keyring;spells
config.sound.play=false
config.ui.window.system.main.height=711
config.ui.window.system.main.width=908
config.predictor.speed=0.541302474394918
config.predictor.jitter=26.232567927131946
